# Generated by Django 4.2.3 on 2023-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_behvarz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behvarz',
            name='date_employee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behvarz',
            name='education',
            field=models.CharField(blank=True, choices=[('High school', '1'), ('Diploma', '2'), ('Associate Degree', '3'), ('Bachelor degree', '4')], max_length=20, null=True),
        ),
    ]
