# Generated by Django 4.2.3 on 2023-07-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_behvarz_date_employee_behvarz_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behvarz',
            name='date_employee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='behvarz',
            name='education',
            field=models.CharField(blank=True, choices=[('High school', 'High school'), ('Diploma', 'Diploma'), ('Associate Degree', 'Associate Degree'), ('Bachelor degree', 'Bachelor degree')], max_length=20, null=True),
        ),
    ]
