# Generated by Django 4.2.3 on 2023-07-15 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_behvarz_date_employee_alter_behvarz_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='date_employee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='date_employee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='behvarz',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behvarz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
