# Generated by Django 4.2.3 on 2023-08-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_birthday_customuser_education_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Behvarz',
        ),
    ]
