# Generated by Django 4.2.3 on 2023-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_q',
            field=models.CharField(blank=True, choices=[('1', 'نام اولین دبیر شما چه بود؟'), ('2', 'نام بهترین کتابی که خوانده اید چه بود؟'), ('3', 'نام رنگ مورد علاقه شما چیست؟'), ('4', 'غذای مورد علاقه شما چیست؟')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/users_avatar/'),
        ),
    ]
