# Generated by Django 4.2.3 on 2023-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0001_initial'),
        ('accounts', '0012_customuser_security_key_customuser_security_q_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='devices',
            field=models.ManyToManyField(blank=True, to='temps.device'),
        ),
    ]
