# Generated by Django 4.2.3 on 2023-07-20 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pdf_file', models.FileField(null=True, upload_to='instructions/pdf_files/', verbose_name='Instruction PDF')),
                ('image_file', models.ImageField(null=True, upload_to='instructions/image_files/', verbose_name='Instruction Image')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('for_behvarz', models.BooleanField(default=False)),
                ('for_expert', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created', '-datetime_updated'],
            },
        ),
    ]
