# Generated by Django 4.2.3 on 2023-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['-datetime_updated', '-datetime_created']},
        ),
        migrations.AddField(
            model_name='instruction',
            name='type',
            field=models.CharField(blank=True, choices=[('instruction', 'Instruction'), ('journal', 'Journal'), ('appreciation', 'Appreciation'), ('text', 'Text'), ('video', 'Video'), ('audio', 'Audio')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='instructions/image_files/', verbose_name='Instruction Image'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='instructions/pdf_files/', verbose_name='Instruction PDF'),
        ),
    ]
