# Generated by Django 4.2.3 on 2023-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_alter_instruction_options_instruction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='status',
            field=models.CharField(blank=True, choices=[('drf', 'Draft'), ('pub', 'Published')], default='drf', max_length=3, null=True),
        ),
    ]
