# Generated by Django 4.2.3 on 2023-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_instruction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ادرس  آی پی')),
            ],
        ),
        migrations.AlterField(
            model_name='instruction',
            name='type',
            field=models.CharField(blank=True, choices=[('instruction', 'دستورالعمل'), ('journal', 'مقاله'), ('appreciation', 'تشویق نامه'), ('text', 'متن'), ('video', 'ویدئو'), ('audio', 'صوت'), ('image', 'تصویر')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='instructions.ipaddress', verbose_name='بازدیدها'),
        ),
    ]
