# Generated by Django 4.2.3 on 2023-08-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_ipaddress_alter_instruction_type_instruction_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Instruction_attach/')),
                ('ins_attach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_attach', to='instructions.instruction')),
            ],
        ),
    ]
