# Generated by Django 4.2.3 on 2023-08-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_attachment_file_name_attachment_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Instruction_attach/'),
        ),
    ]
