# Generated by Django 4.2.3 on 2023-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0007_remove_instruction_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
