# Generated by Django 4.2.3 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0008_attachment_download_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
