# Generated by Django 4.2.3 on 2023-09-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField()),
                ('fw_version', models.CharField(max_length=100)),
                ('sensor_count', models.IntegerField()),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('pcb', models.CharField(max_length=100)),
                ('cid', models.IntegerField()),
                ('lot', models.CharField(max_length=100)),
                ('zone', models.FloatField()),
                ('measurement_delay', models.IntegerField()),
                ('moving_avg', models.IntegerField()),
                ('user_alarm_config', models.IntegerField()),
                ('user_clock_config', models.IntegerField()),
                ('alarm_indication', models.IntegerField()),
                ('temp_unit', models.CharField(max_length=10)),
                ('report_history_length', models.IntegerField()),
                ('det_report', models.IntegerField()),
                ('use_ext_devices', models.IntegerField()),
                ('test_res', models.IntegerField()),
                ('test_ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_signature', models.CharField(max_length=100)),
                ('data_signature', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temps.device')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.IntegerField()),
                ('offset', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='temps.device')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_temp', models.FloatField()),
                ('min_temp_time', models.TimeField()),
                ('max_temp', models.FloatField()),
                ('max_temp_time', models.TimeField()),
                ('avg_temp', models.FloatField()),
                ('alarm0_time', models.IntegerField()),
                ('alarm1_time', models.IntegerField()),
                ('timeout_time', models.IntegerField()),
                ('events', models.IntegerField()),
                ('checked_am_time', models.TimeField(blank=True, null=True)),
                ('checked_pm_time', models.TimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temps.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_al0', models.FloatField(default=0.0)),
                ('t_al_time0', models.IntegerField(default=0)),
                ('t_al1', models.FloatField(default=0.0)),
                ('t_al_time1', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temps.device')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField()),
                ('lot', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('valid_from', models.DateTimeField()),
                ('owner', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='temps.device')),
            ],
        ),
    ]
