# Generated by Django 4.2.3 on 2023-09-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0005_deviceinformation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fault',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='temps.device'),
        ),
    ]
