# Generated by Django 4.2.3 on 2023-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_attachment_alter_label_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
