# Generated by Django 4.2.3 on 2023-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_comment_read_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='read_by_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
