# Generated by Django 4.2.3 on 2023-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_comment_read_by_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='read_by_superuser',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='read_by_user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='read_by_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='read_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
